# Generated by Django 3.0.7 on 2020-06-03 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='description',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='sede',
        ),
    ]
