# Generated by Django 3.0.2 on 2020-06-03 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200603_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='sede',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='comment',
            new_name='description',
        ),
    ]
